#!/bin/bash

#
# Author : Nicolas GUILLAUME <ng@ngsoft-fr.com>
#
#

SERVER="http://api.babeuk.net/vdm/plaintext.php"
if ( echo $LANG | grep -i utf ) > /dev/null 2>&1
then
  CS=UTF-8
else
  CS=ISO-8859-15
fi

function show_help()
{
    echo "usage : vdm [option] [-p n]"
    echo "      Options possibles :"
    echo "          -h        affiche l'aide"
    echo "          -r        affiche une VDM aleatoire"
    echo "          -l        affiche les 15 dernieres VDM"
    echo "          -t        affiche le top"
    echo "          -f        affiche le flop"
    echo "          -p n      affichage la page n"
}


function show_vdm()
{
    curl "${SERVER}?act=$1&pg=$2&t=$RANDOM"  2>/dev/null |  iconv -f UTF-8 -t $CS
    echo
}

act=random
page=0

while getopts "hrltfp:" opt
do
  case $opt in 
      r)
	  act=random
	  ;;
      l)
	  act=last
	  ;;
      t)
	  act=top
	  ;;
      f)
	  act=flop
	  ;;
      p)
	  page=$OPTARG
	  ;;

      * )
	  show_help
	  exit
	  ;;
        esac   
done

show_vdm $act $page

